Define `zero(::StaticInt)`
The motivation is that we have this on Julia nightly:
```julia
julia> zero(static(9))
ERROR: TypeError: in typeassert, expected StaticInt{9}, got a value of type StaticInt{0}
Stacktrace:
 [1] convert
   @ ./number.jl:7 [inlined]
 [2] oftype(x::StaticInt{9}, y::Int64)
   @ Base ./essentials.jl:469
 [3] zero(x::StaticInt{9})
   @ Base ./number.jl:308
 [4] top-level scope
   @ REPL[11]:1
```
The type assert was added (versus Julia 1.8) because of invalidations.